# Generated by Django 2.2.6 on 2020-08-19 10:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('sbs', '0003_logs_ip'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='athlete',
            options={'default_permissions': (), 'managed': True, 'ordering': ['pk']},
        ),
    ]
