# Generated by Django 2.2.6 on 2020-08-19 10:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('sbs', '0004_auto_20200819_1043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='athlete',
            options={'managed': False, 'ordering': ['pk']},
        ),
    ]
