# Generated by Django 2.2.6 on 2020-08-19 11:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('sbs', '0005_auto_20200819_1044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='athlete',
            options={},
        ),
    ]
