# Generated by Django 2.2.6 on 2020-08-19 11:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('sbs', '0007_auto_20200819_1120'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Compathleteforsearch',
        ),
    ]
