# Generated by Django 2.2.6 on 2020-08-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sbs', '0008_delete_compathleteforsearch'),
    ]

    operations = [
        migrations.AddField(
            model_name='preregistration',
            name='isCoach',
            field=models.BooleanField(choices=[(True, 'Evet '), (False, 'Hayır')], default=False),
        ),
    ]
