# Generated by Django 2.2.6 on 2020-08-26 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('sbs', '0009_preregistration_iscoach'),
    ]

    operations = [
        migrations.AddField(
            model_name='preregistration',
            name='iban',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='İban Adresi'),
        ),
        migrations.AddField(
            model_name='preregistration',
            name='kademe_belge',
            field=models.FileField(blank=True, null=True, upload_to='dekont/', verbose_name='Belge'),
        ),
        migrations.AddField(
            model_name='preregistration',
            name='kademe_definition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sbs.CategoryItem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preregistration',
            name='kademe_startDate',
            field=models.DateField(blank=True, null=True, verbose_name='Başlangıç Tarihi '),
        ),
    ]
